spring:
  datasource:
    url: jdbc:h2:mem:h2test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false
  rabbitmq:
    host: 119.23.18.196
    username: root
    password: 123456
    port: 5672
    virtual-host: /
    publisher-confirms: true
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual
  redis:
    host: 119.23.18.196
    port: 6379

zk:
  curator:
    retryCount: 5
    elapsedTimeMs: 5000
    connectString: 119.23.18.196:2181
    sessionTimeoutMs: 60000
    connectionTimeoutMs: 5000





logging:
  level:
    root: info
