server:
  port: 10003


rpc:
  client:
    enable: true
    serviceNames: oss-service
  curatorProperties:
    retryCount: 5
    elapsedTimeMs: 5000
    connectString: 119.23.18.196:2181
    sessionTimeoutMs: 60000
    connectionTimeoutMs: 5000

spring:
  application:
    name: oss-service